export {default as Food} from './Food'
export {default as MMMM} from './MMMM'
export {default as Parrot} from './Parrot'
export {default as Welcome} from './Welcome'
export {default as WiFi} from './WiFi'